### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by T9es** [papuSpartan/stable-diffusion-webui-distributed#13]
Ever since trying to set this up, I've gotten this error. The console doesn't show anything as of now, but before, it would show that error and that some extensions are not supported (I've disabled them since then)

Never mind that "nothing in the console", managed to get the console log:

```
To create a public link, set `share=True` in `launch()`.
Startup time: 69.3s (import torch: 6.3s, import gradio: 1.5s, import ldm: 0.7s, other imports: 1.2s, setup codeformer: 0.1s, load scripts: 44.0s, load SD checkpoint: 2.8s, create ui: 10.0s, gradio launch: 2.5s).
                                  WARNING  config reports invalid speed (0 ipm) for worker 'argon', setting default of 1 ipm.                 World.py:378
         please re-benchmark
Error completing request

Traceback (most recent call last):
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\extension.py", line 291, in run
    Script.world.optimize_jobs(payload)  # optimize work assignment before dispatching
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\spartan\World.py", line 402, in optimize_jobs
    lag = self.job_stall(job.worker, payload=payload)
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\spartan\World.py", line 330, in job_stall
    lag = worker.batch_eta(payload=payload, quiet=True) - fastest_worker.batch_eta(payload=payload, quiet=True)
  File "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\spartan\Worker.py", line 210, in batch_eta
    eta = (num_images / self.avg_ipm) * 60
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
```

Edit: Might want to specify more, I'm running python 3.10.10. If any info is required further, let me know.

**Comment by solareon** [comment]
I believe this is the same issue as this https://github.com/Kilvoctu/aiyabot/issues/194#issuecomment-1625998975
Something to do with "sd-webui-color-enhance" extension. If you disable that it may fix this issue.

**Comment by T9es** [comment]
Sadly, that wasn't it. There is still the same error. I disabled all extensions and it still persists

**Comment by papuSpartan** [comment]
What are your exact launch arguments when having this issue

**Comment by T9es** [comment]
The first instance: 

`set COMMANDLINE_ARGS= --port 7861 --xformers --no-half-vae --opt-sdp-attention --medvram --ckpt-dir "R:\Stable diffusion\Stable-diffusion" --opt-channelslast --distributed-remotes RTX2060:localhost:7860 argon:fake.local:7860 --distributed-skip-verify-remotes --distributed-remotes-autosave`

The second instance:

`--api --port 7860 --xformers --no-half-vae --opt-split-attention --medvram --ckpt-dir "R:\Stable diffusion\Stable-diffusion" --embeddings-dir "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\embeddings" --lora-dir "Y:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\models\Lora" --listen`

**Comment by papuSpartan** [comment]
@T9es It looks like you are using the example config which would be looking for a worker at `fake.local` which I would assume doesn't exist on your network. If you remove that entry from `--distributed-remotes`, and hit `re-benchmark` under the utils tab in the script's section, you may have more luck.

**Comment by T9es** [comment]
Huh, that's actually weird. I figured it would be that fake.local causing issues, when I removed it yesterday, it was still spewing out errors.

The fix: I went through stable diffusion folders, re-installed all VENV, and only after that, removing the fake.local worked. Avoided re-installing in the first place, since I have a really bad connection, so downloading would take several hours
