### ISSUE TITLE
Is there a way to always enable this extension

### ISSUE THREAD

**Issue by GoldenDog1218** [papuSpartan/stable-diffusion-webui-distributed#18]
Is there a way to always enable this extension?
I am running a free service to generate images, so I have created three GPUs to do this, so I hope this extension can always be enabled so that others do not need to manually enable plugins

**Comment by papuSpartan** [comment]
For now, you can have the script enabled by default by setting the following entries in `ui-config.json`:

```
"txt2img/Script/value": "Distribute",
"img2img/Script/value": "Distribute"
```

You can also use the view changes utility in `Settings Tab -> Defaults`
