### ISSUE TITLE
ERROR config is corrupt or invalid JSON

### ISSUE THREAD

**Issue by ttyler3** [papuSpartan/stable-diffusion-webui-distributed#21]
When attempting to run stable diffusion with this extension enabled, it gives me an error stating "config is corrupt or invalid JSON   World.py:527". I am attempting to run a slave instance on localhost with a different GPU than master. Unsure if I am specifying the slave GPU correctly, but my guess is it should not affect the "World.py" error that was thrown.

**Comment by papuSpartan** [comment]
Please post your startup logs from where it failed or upload distributed.log from the extension folder.7jm
