### ISSUE TITLE
error with multiprompt generation

### ISSUE THREAD

**Issue by yggdrasil75** [papuSpartan/stable-diffusion-webui-distributed#24]
```
*** Error running before_process: D:\non-docker\illyforge\extensions\stable-diffusion-webui-distributed\scripts\distributed.py
    Traceback (most recent call last):
      File "D:\non-docker\illyforge\modules\scripts.py", line 795, in before_process
        script.before_process(p, *script_args)
      File "D:\non-docker\illyforge\extensions\stable-diffusion-webui-distributed\scripts\distributed.py", line 342, in before_process
        payload_temp['subseed'] += prior_images
    TypeError: 'int' object is not iterable
```
I have a script generating multiple images using different prompts (different seeds, subseeds, negative prompt). I want to distribute the script over different gpus and devices.
unfortunately, I get the above error. is there an easy way to hook into distributed and add a queue of requests which it will automatically split based on the estimated ipm, when distributed is enabled?

**Comment by papuSpartan** [comment]
```python
        payload_temp['subseed'] += prior_images
    TypeError: 'int' object is not iterable
```

Has payload_temp become an integer? It should be a dict containing key 'subseed' which should also be an integer. payload_temp is ultimately just a [copy of p](https://github.com/papuSpartan/stable-diffusion-webui-distributed/blob/40d5afd7cb0a21967835506c7080b7c803661e35/scripts/distributed.py#L283) at the time of before_process() executing.

>  is there an easy way to hook into distributed and add a queue of requests

Distributed does not utilize a queue of its own but instead relies on sdwui's queue. That being said, you could just make your own queue if necessary. If you get a reference to Distributed's instance of World, there are methods for that class which make executing requests simple. This does assume though that you adhere to at least most of the formatting of sdwui's internal p and processed objects.

**Comment by papuSpartan** [comment]
> I will note: p.subseed becomes list[int] when multiple p are merged instead of a single int

Shouldn't that be done with p.all_subseeds instead of [p.subseed](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/33c8fe1221cdc53b9f00b7041b6e06cc9b0e037c/modules/processing.py#L149)?

**Comment by papuSpartan** [comment]
> unfortunately, that doesn't appear to be the issue. I will continue testing and try to determine what is causing this incompatibility as my script really could use even more speedup.

Have you been able to narrow this down? I'm going to be looking more into improving external script/extension compatibility so let me know if you do and we can reopen this.
