### ISSUE TITLE
Multiple workers function until I change the resolution of the output on the master server.

### ISSUE THREAD

**Issue by cul8rmom1** [papuSpartan/stable-diffusion-webui-distributed#33]
Awesome extension.
I have copied the entire install directory between all of the machines to make sure everything is apples to apples.
This is the start command line on the 2 remote workers.
set COMMANDLINE_ARGS= --theme dark --xformers --listen --api --api-server-stop.

Running windows 10/11 with all virus scan/firewall etc turned off.

Everything works great until...
![image](https://github.com/user-attachments/assets/c1e97287-2304-4c92-8d1f-2131d43a5ba5)

I can do the benchmark and it runs on all nodes.
![image](https://github.com/user-attachments/assets/9f3f45cd-94b5-44bd-87e1-1bf3ea2a1726)
![image](https://github.com/user-attachments/assets/33f6a6cb-ccfa-47a4-b923-daeab2ddb8ab)
![image](https://github.com/user-attachments/assets/cd41aa36-35de-42fc-b3f7-3bc5b295f4af)
All good in the hood.
Now I change the resolution.
Then it says "DISTRIBUTED | DEBUG    distributed has nothing to do, returning control to webui                               distributed.py:303"
![image](https://github.com/user-attachments/assets/42f669b5-0d88-428d-9ed7-88d614f2569d)

I turn complimentary back on and it creates a crap ton of extra on the slower nodes.
![image](https://github.com/user-attachments/assets/260a931d-4b50-4822-93fe-6041a4dc6b5a)

I will jump in discord and see who says what.
Let me know if there is any other information I can provide.

Thanks!!

**Comment by papuSpartan** [comment]
I can't go through this all immediately. However, know that you should only need the extension installed on a single instance. The other instances merely need their api exposed so that you can add them in the main instance.

**Comment by papuSpartan** [comment]
The solution in this case was to increase batch size before iterations/batch count
