### ISSUE TITLE
Grid generation doesn't include slave output

### ISSUE THREAD

**Issue by solareon** [papuSpartan/stable-diffusion-webui-distributed#5]
When running with loads that span across multiple slaves the output doesn't include a grid with all of the combined images. Only the grid from a single slave is shown. Example from my 4 instances below.

![image](https://github.com/papuSpartan/stable-diffusion-webui-distributed/assets/769465/4dc75f09-7960-4686-bda8-9b5c28aada72)

**Comment by papuSpartan** [comment]
That should be the grid from master not any slave. No grids should ever be returned for slaves because i hadn't implemented it yet. Should be relatively easy to add.

**Comment by solareon** [comment]
Agree that it's the grid from the master. My understanding of how the A1111 repo returns grids is kind of limited. My only experience has been running it with the API side using the Aiya discord bot where I had to build the grids manually. It would be cool if it would return just a single grid merging all the outputs from the slaves.

**Comment by solareon** [comment]
Almost have this fixed. Just resolving a list index out of range due to generating the grid at the end. It works but if you try to save it barfs.
