### ISSUE TITLE
Job counts that are not even multiples of number of slaves behaves oddly

### ISSUE THREAD

**Issue by solareon** [papuSpartan/stable-diffusion-webui-distributed#6]
If you use a batch size that is not evenly divisible by the number of workers available the remainder of the batch is not generated. With 4 workers and a batch size of 25 you should see a generation task like 7/6/6/6 instead it does 6/6/6/6 and drops the remaining batch count.

**Comment by papuSpartan** [comment]
should be fixed in dev
